name: release
on:
  push:
    branches: [main]
jobs:
  test:
    name: Test for release
    if: startsWith(github.event.head_commit.message, '[release:minor]') ||
      startsWith(github.event.head_commit.message, '[release:major]') ||
      startsWith(github.event.head_commit.message, '[release:patch]')
    uses: Code-Inspect/vscode-flowr/.github/workflows/test.yml@main

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.x
          registry-url: 'https://registry.npmjs.org/'
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          step=$(echo "$MESSAGE" | sed -n -E 's/\[release:(patch|minor|major)].*/\1/p')
          if [ -z "$step" ]; then
            echo "fatal: Release step not found in commit message."
            exit 1
          fi

          new_version=$(npm version "$step" -m "[skip ci] Release %s")
          echo "PACKAGE_VERSION=$new_version" >> $GITHUB_ENV
        env:
          # apparently, putting the message into an env variable first sanitizes it
          # (see https://github.com/Code-Inspect/flowr/security/code-scanning/29)
          MESSAGE: ${{ github.event.head_commit.message }}

      - name: Package
        run: vsce package

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: vscode-flowr-*.vsix
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: ${{ vars.PACKAGE_VERSION }}
      - name: Push version update
        run: |
          git push
          git push --tags
